config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  devise_for :users

  resources :missions
  resources :users, only: [:index, :show, :update, :destroy]
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user

  validates_presence_of :title, :description
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  before_action :set_mission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new(new_mission_params)
    @mission.user = current_user

    if @mission.save
      redirect_to @mission, notice: "Mission was successfully created!"
    else
      render :new
    end
  end

  def index
    @missions = Mission.all
  end

  def show
  end

  def edit
    if current_user.id != @mission.user_id
      redirect_to @mission, notice: 'You are not authorized to edit this mission!'
    end
  end

  def update
    if @mission.update(new_mission_params)
      redirect_to @mission, notice: "Mission was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    if current_user.id != @mission.user_id
      redirect_to @mission, notice: 'You are not authorized to delete this mission!'
    else
      @mission.destroy
      redirect_to missions_url, notice: "Mission was successfully deleted!"
    end
  end

  private

  def set_mission
    @mission = Mission.find(params[:id])
  end

  def new_mission_params
    params.require(:mission).permit(:title, :description)
  end
end

app/views/missions/_mission_form.html.erb
<div class="callout">
  <%= form_for(@mission) do |f| %>
    <% if @mission.errors.any? %>
      <div id="error_explanation">
        <p><%= pluralize(@mission.errors.count, "error") %> prohibited this mission from being saved:</p>

        <ul>
          <% @mission.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :title, "Title:" %><br />
      <%= f.text_field :title, id: :mission_title %>
    </div>

    <div class="field">
      <%= f.label :description, "Description:" %><br />
      <%= f.text_area :description, id: :mission_description %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/missions/edit.html.erb
<div class="callout">
  <h1>Edit This Mission</h1>
  <h5><%= link_to 'Cancel Update', mission_path %></h5>

  <%= render partial: 'mission_form', mission: @mission %>
</div>

app/views/missions/index.html.erb
<div class="callout">
  <h1>All Missions</h1>

  <h3><%= link_to 'Submit a New Mission!', new_mission_path %></h3>

  <div class="callout">
    <% if @missions == [] %>
      <p>No missions have been submitted</p>
    <% else %>
      <% @missions.each do |mission| %>
        <li><%= link_to "#{mission.title} - #{mission.user.full_name}", mission %></li>
      <% end %>
    <% end %>
  </div>
</div>

app/views/missions/new.html.erb
<div class="callout">
  <h1>Submit New Mission</h1>
  <h5><%= link_to 'Back to All Missions', missions_path %></h5>

  <%= render partial: 'mission_form', mission: @mission %>
</div>

app/views/missions/show.html.erb
<div class="callout">
  <h1>Selected Mission</h1>
  <h5><%= link_to 'Back to All Missions', missions_path %></h5>

  <div class="callout">
    <h3><%= @mission.title %></h3>
    <h4><%= @mission.description %></h4>
    <p>Submitted by: <%= @mission.user.full_name %></p>
    <p>Submitted at: <%= @mission.created_at.strftime("%B %e, %Y") %></p>
  </div>

  <h5><%= link_to 'Edit this Mission', edit_mission_path %></h5>
  <h5><%= link_to 'Delete this Mission', @mission, method: :delete, data: { confirm: 'Are you sure you want to delete this mission?' } %></h5>
</div>